ALTER TABLE "CustomerCell"
ADD COLUMN "planCode" TEXT NOT NULL DEFAULT 'UNASSIGNED',
ADD COLUMN "allowedModules" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "CustomerCell" ALTER COLUMN "planCode" DROP DEFAULT;
